### ISSUE TITLE
No physical interface description

### ISSUE THREAD

**Issue by John-Titor** [inferiorhumanorgans/DS2PlusPlus#1]
It'd be super handy to have a comment somewhere in the code that described the physical interface that this is expecting, since DS2 runs over the K-line and so it's not logic-level serial or RS-232.

Doesn't seem to be any ELM327 control in there, so not that. Talking to a K+DCAN serial dongle? Wired direct via a level shifter?

Inquiring / reusing minds would like to know!

**Comment by inferiorhumanorgans** [comment]
It should work with any serial to K-line (or presumably K+DCAN) dongle.  I use a serial cable with a separate USB adapter (both PL2303 and FTDI adapters work for me).

**Comment by John-Titor** [comment]
Thanks - I managed to get it going with nothing more than a LIN transceiver in the end; I was expecting it to be more complicated than it actually was...
